[phases.setup]
nixPkgs = ["python311", "gcc", "python311Packages.pip"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Python Flask application build complete'"]

[start]
cmd = "python index.py"

[variables]
PYTHON_VERSION = "3.11.7"
NODE_VERSION = "none"
