[phases.setup]
nixPkgs = ["python311", "gcc", "python311Packages.pip"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Python Flask application build complete'"]

[start]
cmd = "python -m gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
