[build]
builder = "nixpacks"

[deploy]
startCommand = "python index.py"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 300
numReplicas = 1

[variables]
PYTHON_VERSION = "3.11.7"
NODE_VERSION = "none"
